version: "3.2"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  postgres:
    # if you build image locally and tagged it as "postgres_mysql"
    #image: postgres_mysql

    # if you want to use prebuilt image
    image: toleg/postgres_mysql
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

