version: "3.2"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  postgres:
    image: postgres_mysql
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

